[book]
title = "Laer Inage Concept Cube 141"
authors = ["FleetingLore <Macro__9@outlook.com>"]
language = "zh-CN"
description = "https://github.com/localLore/laer-image-concept-cube141"

[build]
build-dir = "book"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/localLore/laer-image-concept-cube141"
site-url = "/laer-image-concept-cube141/"

[output.html.fold]
enable = true
level = 1
